### ISSUE TITLE
Linker issues

### ISSUE THREAD

**Issue by Dids** [sushihangover/Realm.Json.Extensions#12]
By default, Xamarin Studio projects set `Linker behavior` to `Link Framework SDKs Only`, which nicely reduces the size of the binary, however this breaks with the Realm JSON extension and throws the following:

*iOS*
```
MTOUCH: error MT2002: Failed to resolve "Realms.RealmObject Realms.Realm::ObjectForPrimaryKey(System.String,System.Nullable`1<System.Int64>)" reference from "Realm, Version=0.80.0.0, Culture=neutral, PublicKeyToken=null"
```

*Android*
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Error executing task LinkAssemblies: error XA2006: Reference to metadata item 'Realms.RealmObject Realms.Realm::ObjectForPrimaryKey(System.String,System.Nullable`1<System.Int64>)' (defined in 'RealmJson.Extensions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null') from 'RealmJson.Extensions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null' could not be resolved.
```

From what I can tell, it's stripping Realm and/or the Realm JSON extension symbols, which causes the compilation errors above.

While this can be worked around by disabling linking completely, that's far from an optimal solution.

**Comment by sushihangover** [comment]
Pushed new Nuget package: https://www.nuget.org/packages/RealmJson.Extensions/

Release: https://github.com/sushihangover/Realm.Json.Extensions/releases/tag/1.1.2

Closes: #13 

@Dids Please test by updating the RealmJson.Extension package a 1.1.2 and compiling w/ Linker set to SDK Only or Full

**Comment by Dids** [comment]
Both platforms now work perfectly fine, thank you! :)

**Comment by sushihangover** [comment]
Thanks for the bug report. Glad everything is working.
